# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date created')),
                ('logins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=600)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postsubjectivity.Alias')),
            ],
        ),
    ]
