# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsubjectivity', '0003_alias_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='alias',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
