# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsubjectivity', '0004_auto_20171122_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='src',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='embedding',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
